# Generated by Django 6.0.2 on 2026-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='defaultuser', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
